I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 22, in script call
    call expression act
  File "game/script.rpy", line 27, in script
    $ act = fight.resolution_phase()
  File "game/script.rpy", line 27, in <module>
    $ act = fight.resolution_phase()
AttributeError: 'FFCombatant' object has no attribute 'atk'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 22, in script call
    call expression act
  File "game/script.rpy", line 27, in script
    $ act = fight.resolution_phase()
  File "F:\Development\RenPy\renpy-6.15.7-sdk\renpy\ast.py", line 785, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "F:\Development\RenPy\renpy-6.15.7-sdk\renpy\python.py", line 1448, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 27, in <module>
    $ act = fight.resolution_phase()
  File "F:\Development\RenPy\Fast Fight Engine/game\scripts\ffe_engine.py", line 52, in resolution_phase
    self.actions_resolution("fast")
  File "F:\Development\RenPy\Fast Fight Engine/game\scripts\ffe_engine.py", line 84, in actions_resolution
    self.resolution(summary)
  File "F:\Development\RenPy\Fast Fight Engine/game\scripts\ffe_engine.py", line 117, in resolution
    for key in self.actor.atk:
AttributeError: 'FFCombatant' object has no attribute 'atk'

Windows-7-6.1.7601-SP1
Ren'Py 6.99.4.467
Fast Fight Engine 0.1
